site_name: nvim-lspconfig
site_url: https://nvim-lsp.github.io/
repo_url: https://github.com/neovim/nvim-lspconfig/
edit_uri: https://github.com/nvim-lsp/nvim-lsp.github.io/edit/main/docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)" 
      primary: green
      accent: green
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      primary: green
      accent: green
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - sane_lists
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neovim/nvim-lspconfig
nav:
  - Home: index.md
  - Install: install.md
  - Configurations:
    - Introduction: configurations/index.md
    - Configurations:
      - AUTOMATED: configurations/index.md
  - Help:
    - What is nvim-lspconfig?: help/index.md
    - Autocompletion: help/autocomplete.md
    - Code Actions: help/codeaction.md
    - Comparison to other LSP ecosystems: help/compare.md
    - Complete init.lua example: help/init.md
    - Connecting to remote language servers: help/remote.md
    - Language spesific plugins: help/plugins.md
    - Project local setting: help/local.md
    - Running language servers in containers: help/containers.md
    - Snippets: help/snippets.md
    - UI Customization: help/customization.md
    - Understanding setup {}: help/setup.md
    - User contributed tips: help/tips.md
